export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';

export const FETCH_PHOTO_DETAIL = 'FETCH_PHOTO_DETAIL';
export const FETCH_PHOTO_DETAIL_START = 'FETCH_PHOTO_DETAIL_START';
export const FETCH_PHOTO_DETAIL_SUCCESS = 'FETCH_PHOTO_DETAIL_SUCCESS';
export const FETCH_PHOTO_DETAIL_FAIL = 'FETCH_PHOTO_DETAIL_FAIL';

export const CLEAN_STATE_PHOTO_DETAIL = 'CLEAN_STATE_PHOTO_DETAIL';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
